### ISSUE TITLE
is there any side-effect already known?

### ISSUE THREAD

**Issue by luoqisheng** [keith/swift-staticlibs#11]

**Comment by keith** [comment]
I’m sorry, I’m not sure what you mean?

Are you just asking if there are any downsides to this? If so I think the list would be:

- You can’t use it with CocoaPods
- You have to manage the resources in your dependencies that previously would’ve been bundled in the framework directories
- This doesn’t work for IBDesiagnables in the frameworks

**Comment by keith** [comment]
Closing this, please feel free to open another issue or respond here if you need any clarification.

**Comment by Unihilator** [comment]
so we still can't use it with cocoapods?

**Comment by keith** [comment]
No, there are no plans to support this now that Xcode 9 beta 4+ officially support Swift static libraries. You can follow the progress of CP adding support for this here: https://github.com/CocoaPods/CocoaPods/issues/6899
