### ISSUE TITLE
LD can't be overridden with Xcode 9's New Build System

### ISSUE THREAD

**Issue by rsebbe** [keith/swift-staticlibs#12]
it's an interesting approach for a number of reasons, and I could make it work in both Xcode 8 and Xcode 9 with the legacy build system.

However, when switching to Xcode 9's New Build System (File > Workspace Settings > New Build System), it appears that the overridden LD Build Setting is not used anymore, and the built framework is a dynamic one.

Any idea if there is a workaround for that?

**Comment by keith** [comment]
Ha. I see this as well. Luckily I just discovered that with the new build system, Xcode 9 natively supports Swift static libraries! So you shouldn't need this at all 🎉

**Comment by keith** [comment]
Outside of that awesome new functionality, there might be a chance this just isn't implemented yet in the new build system, I do see some env vars that should probably be for this (not `LD` specifically, but `LIBTOOL` and `LDPLUSPLUS`) but it doesn't seem like any of them currently work. I will probably file a radar about this soon.

**Comment by rsebbe** [comment]
Exactly, just found out as well, was surprised to see it now accepts static Mach-o type (frameworks).

Straight Swift static libs do build too, but I can't figure out so far how to make the main app find the associated module. Probably some incorrect build settings at this point.

The script might still make sense when we do want to switch from/to NBS in the transitory period (now). Anyway, thank you for sharing.

**Comment by keith** [comment]
It sounds like this might be a bug https://twitter.com/daniel_dunbar/status/878603832103641089 (even though AFAICT everything is working great). So in later betas this might be broken again 😭

**Comment by keith** [comment]
As of Xcode 9 beta 4 it's official that both the new and old build systems support static libraries with Swift sources ([source](https://twitter.com/daniel_dunbar/status/889533883338838016))!

**Comment by rsebbe** [comment]
Great news! We can finally start building reusable code in Swift, without type name conflicts and dyld load overhead… 👍

Thank you for the workaround during the transition.

**Comment by keith** [comment]
CocoaPods is working on adding support for this: https://github.com/CocoaPods/CocoaPods/issues/6899

**Comment by keith** [comment]
Since this is supported in Xcode I'm closing this
