### ISSUE TITLE
GenerateDSYMFile step failed

### ISSUE THREAD

**Issue by xohozu** [keith/swift-staticlibs#13]
For each pod when set **LD** build settings to `/path/to/ld.py`, I got below error.
```
error: cannot parse the debug map for "/path/to/Xcode/DerivedData/hippocampus-bvehpkwwfmhekjgjnnkpqukjfvlj/Build/Products/Release-iphoneos/podname/podname.framework/podname": The file was not recognized as a valid object file
```

**Comment by keith** [comment]
You'll have to disable dsym generation. This won't be a problem for a few reasons:

1. If you disable the dsym generation just for your pods, a dsym can still be generated from your main app, which will include the symbols from the static libraries
2. You're likely using bitcode in which case you don't even use your dsyms for much of anything, and instead you use the ones generated by apple after they generate versions of your app for multiple architectures.

Here's the snippet you'll need to put in your Podfile to disable dsym generation for pods:

```ruby
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings["DEBUG_INFORMATION_FORMAT"] = "dwarf"
    end
  end
end
```

**Comment by xohozu** [comment]
Thanks for your **so fast reply** which saves me much time to fix it.

You said:
> If you disable the dsym generation just for your pods, a dsym can still be generated from your main app, which will include the symbols from the static libraries

Where can I refer to that main app also generated dsym containing those disable pods dsym ?

**Comment by keith** [comment]
Whenever your `App.dSYM` file is, if you run `dwarfdump` on the contained binary, you should be able to see the symbols from your static libraries.

**Comment by xohozu** [comment]
It makes sense.
