### ISSUE TITLE
dyld: Library not loaded: @rpath/Realm.framework/Realm

### ISSUE THREAD

**Issue by Unihilator** [keith/swift-staticlibs#15]
dyld: Library not loaded: @rpath/Realm.framework/Realm
  Referenced from: /Users/Unihilator/Library/Developer/CoreSimulator/Devices/D70A2C2B-D27D-48EC-9C65-A78EF186438C/data/Containers/Bundle/Application/AF1A2EB1-CF96-4C9B-A10F-AE3C998204DD/PodsDependencies.app/PodsDependencies
  Reason: image not found

This happened on app execution. What I need to check to solve this problem?
Thanks)

**Comment by Unihilator** [comment]
btw - I've added this pod to the PodsDependencies test project

**Comment by keith** [comment]
Closing since this doesn't support CocoaPods and I won't be adding support for this, see https://github.com/keith/swift-staticlibs/issues/12 for more details
